###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    memcached:
        image: 'memcached:alpine'

    redis:
        image: 'redis:alpine'

    webserver:
        image: 'nginx:alpine'
        working_dir: /app
        volumes:
            - './app:/app'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '0.0.0.0:3000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /app
        volumes:
            - './app:/app'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
        environment:
            - DB_HOST=127.0.0.1
            - DB_USER=root
            - DB_PASS=root
            - DB_NAME=blog
